org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=1g -Xss512k -Dfile.encoding=UTF-8 -XX:+UseParallelGC -XX:ReservedCodeCacheSize=512m
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configureondemand=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.daemon.jvm.options=-Xmx384m,-XX:MaxMetaspaceSize=256m,-XX:ReservedCodeCacheSize=64m
android.r8.maxWorkers=1
android.r8.gradual.support=true
org.gradle.configuration-cache=false
# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=18080
# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=18080
org.gradle.java.installations.paths=/root/.local/share/mise/installs/java/17.0.2,/root/.local/share/mise/installs/java/21.0.2,/root/.local/share/mise/installs/java/25.0.2
